Import("env")

import os
import subprocess


def _run_git(args):
    try:
        return subprocess.check_output(
            ["git"] + args,
            cwd=env["PROJECT_DIR"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return ""


def resolve_build_id():
    short_sha = _run_git(["rev-parse", "--short=7", "HEAD"])
    if not short_sha:
        return "nogit"

    dirty = _run_git(["status", "--porcelain", "--untracked-files=normal"])
    if dirty:
        return f"{short_sha}-dirty"
    return short_sha


def _c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _write_if_changed(path, content):
    try:
        with open(path, "r", encoding="utf-8") as existing:
            if existing.read() == content:
                return
    except FileNotFoundError:
        pass

    with open(path, "w", encoding="utf-8", newline="\n") as generated:
        generated.write(content)


generated_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(generated_dir, exist_ok=True)

header_path = os.path.join(generated_dir, "AppBuildId.generated.h")
header = (
    "// Generated by scripts/set_build_id.py; do not edit.\n"
    "#pragma once\n\n"
    f"#define APP_BUILD_ID {_c_string(resolve_build_id())}\n"
)

_write_if_changed(header_path, header)
env.Append(CPPPATH=[generated_dir])
